### PR TITLE
feat: Add User Table (#2)

### LINKED ISSUE #2: Table displaying users
## Description
As a user, I want to be able to see the current members of Blueprint. The table will contain the following columns:
- Name
- Email
- Title
- Status (Active, Inactive)

The table should be sorted by alphabetical order and status (Only display active users). 

## Tasks

- [ ] Use Chakra Table Component
- [ ] Pagination
- [ ] API call to fetch users

## Notes on implementation:
ChakraUI provides a Table component. You have to create your own component and add it to ```/components ```. Once you have finished the Table component, you have to add it to ```App.tsx```.

## Example
https://dribbble.com/shots/19408052-Data-Table-Dashboard-Design

### PR DESCRIPTION
**Pull request by cengelbart39**
Adds a Chakra UI Table containing data from `sample_data.json`.

Sorts users by name alphabetically and only shows active users.

Closes #2.

### CODE REVIEW

**Comment by cengelbart39** [comment]
It doesn't like how I'm importing a JSON file. While this just displays a warning by ESLint when running locally, it becomes a problem here.

I'm not sure what's the best course of action to fix this. I could mess with the ESLint config or see if there's another way to import the file that won't run afoul of ESLint.

**Comment by miguel-merlin** [comment]
> It doesn't like how I'm importing a JSON file. While this just displays a warning by ESLint when running locally, it becomes a problem here.
> 
> I'm not sure what's the best course of action to fix this. I could mess with the ESLint config or see if there's another way to import the file that won't run afoul of ESLint.

@cengelbart39 You can run ```npm run lint``` to fix linter warnings

**Comment by cengelbart39** [comment]
I get 'warning: Unexpected use of file extension "json" for "../sample_data.json"  import/extensions' since I'm importing the file. Whether I run 'npm run lint' directly or not.

**Comment by cengelbart39** [comment]
> @miguel-merlin I get `warning: Unexpected use of file extension "json" for "../sample_data.json"  import/extensions` since I'm importing the file, whether I run `npm run lint` directly or not. 

@miguel-merlin Any thoughts on this?

**Comment by miguel-merlin** [comment]
> > @miguel-merlin I get `warning: Unexpected use of file extension "json" for "../sample_data.json"  import/extensions` since I'm importing the file, whether I run `npm run lint` directly or not.
> 
> @miguel-merlin Any thoughts on this?

@cengelbart39 We deployed our backend last week; instead of fetching stuff from the JSON, you can use the API. You'll find it in the ```src/api/lib/users.tsx```. You can use the getAllUsers endpoint which returns the sample JSON. You will have to wrap the API call in a useState hook.

**Comment by miguel-merlin** [comment]
@cengelbart39 I disabled the linter error for now.

**Review by miguel-merlin — APPROVED** [review]
Nice job! Thanks for contributing

**Comment by miguel-merlin** [comment]
@cengelbart39 Merged!

**Pull request merged**
